Fix this and make it readable.

diff --git a/.github/workflows/reusable-deploy-tag.yml b/.github/workflows/reusable-deploy-tag.yml
--- a/.github/workflows/reusable-deploy-tag.yml
+++ b/.github/workflows/reusable-deploy-tag.yml
@@ -172,7 +172,12 @@ jobs:
 
     - name: Close completed milestone
       run: | #shell
-        ID=$(gh api "/repos/${GITHUB_REPOSITORY}/milestones" --jq '.[] | select(."title" == "${WP_VERSION}") | ."number"')
+        JQ_FILTER='.[] | select(.title == "'"${WP_VERSION}"'") | .number'
+        ID="$(gh api "/repos/${GITHUB_REPOSITORY}/milestones" --jq "$JQ_FILTER")"
+        if [ -z "$ID" ]; then
+            echo "Milestone not found for version ${WP_VERSION}"
+            exit 1
+        fi
         gh api "/repos/${GITHUB_REPOSITORY}/milestones/${ID}" --method "PATCH" --field "state=closed"
       env:
         GITHUB_TOKEN: ${{ github.token }}
